### ISSUE TITLE
AH01071 Class 'Symfony\\Component\\WebLink\\HttpHeaderSerializer' not found

### ISSUE THREAD

**Issue by Hotte512** [FriendsOfShopware/FroshPerformance#1]
## Actual behaviour

After Plugin activation (upload & install via Admin-Backend) Shop gives me a 500 and i get this errorin my apache Log:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'Symfony\\Component\\WebLink\\HttpHeaderSerializer' not found in /var/www/vhosts/domain.tld/httpdocs/_dev/custom/plugins/FroshPerformance/Subscriber/Http2PushSubscriber.php:31\nStack trace:\n#0 /var/www/vhosts/domain.tld/httpdocs/_dev/var/cache/production_201807181357/proxies/ShopwareProductionb4c331d59c46c252f54e4e6f5d97e3b102f513a8ProjectContainer.php(1405): FroshPerformance\\Subscriber\\Http2PushSubscriber->__construct(Array)\n#1 /var/www/vhosts/domain.tld/httpdocs/_dev/vendor/symfony/dependency-injection/Container.php(297): ShopwareProductionb4c331d59c46c252f54e4e6f5d97e3b102f513a8ProjectContainer->getFroshPerformance_Subscriber_Http2Service()\n#2 /var/www/vhosts/domain.tld/httpdocs/_dev/engine/Shopware/Components/DependencyInjection/Container.php(211): Symfony\\Component\\DependencyInjection\\Container->get('frosh_performan...', 1)\n#3 /var/www/vhosts/domain.tld/httpdocs/_dev/engine/Shopware/Components/DependencyInjection/Container...\n'

(There is no core.log in sw/var/log)

## Expected behaviour

    Faster Frontend ;-)

## Environment

    Apache/2.4.25 (Debian), PHP/7.0.31(FPM), Shopware/5.4.6

## Steps to reproduce

1. Upload Plugin.zip + Installl + Activate

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
Run composer install in the plugin folder

**Comment by DanielRuf** [comment]
Well then the installation instructions are not complete I guess.

https://github.com/FriendsOfShopware/FroshPerformance

```
Installation
Download latest release
Extract the zip file in shopware_folder/custom/plugins/
```
