### ISSUE TITLE
LESS files are not loading as normal, mixed up frontend view from different subshops

### ISSUE THREAD

**Issue by klausmad** [FriendsOfShopware/FroshPerformance#13]
## Actual behaviour

If html minify of the performance plugin is activ, the LESS files are not loading as normal, the colours and shop-logo is mixed up from 3 different subshop.

>>> Looks like this...all what is orange coloured should be normaly blue like a other subshop in the same system.

![grafik](https://user-images.githubusercontent.com/22545981/51387481-6d6bcf80-1b26-11e9-8aec-d638de04d530.png)

>>> This is the correct standardview without performance plugin

![grafik](https://user-images.githubusercontent.com/22545981/51387672-2f22e000-1b27-11e9-8be0-e7d600c85f69.png)

## Environment

SW 5.5.4 prof.  on apache 2.4 with PHP 7.0.30 Plugin version 1.0.2
Settings

![grafik](https://user-images.githubusercontent.com/22545981/51387820-c4be6f80-1b27-11e9-9784-09004f028f72.png)

## Steps to reproduce

1. Please send me PM, if you are online, I will activate the plugin so you can see it online what happens

## Checklist

- [x ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ x] I am using the latest stable version of this plugin.

--

EDIT: I have seen now, all parts of the frontendview they get problems with the performance plugin and html minify are from the same developer. I will also inform this developer, about this issue.

![grafik](https://user-images.githubusercontent.com/22545981/51388253-1fa49680-1b29-11e9-8ce1-adc34ddc388b.png)

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
Wenn du die HTML Komprimierung ausstellst, funktioniert es dann?

**Comment by klausmad** [comment]
Hallo, shyim, korrekt....deaktiviere ich die Komprimierung ist in allen 4 Shops alles in Ordnung. Aktiviere ich das Plugin, dann werden alle Farben vertauscht, das betrifft jedoch alle Plugins (bewußt von einem Entwickler, damit die Kompatibilität passt) wie Hinweisleiste, Angebote Sales, Shipping Icon,Payment Icon wie oben rot markiert.
Hatte zuvor HTML Komprimierung von WOTipps im Einsatz,( https://github.com/niklasbuechner/WOTippsHTML ) da tritt das Problem nicht auf.
Vermute es wird irgendwie die JS zerschossen die die Darstellung der Banner und Leisten von Zenit aufruft... habe bei Zenit auch ein Ticket aufgemacht...sprecht euch zusammen...zenit Plugins sind doch stark verbreitet...

LG Klaus

**Comment by shyim** [comment]
Ich versuch das mal zu reproduzieren mit mehreren Subshops :)

**Comment by klausmad** [comment]
Danke Dir,

so ist mein Aufbau

![grafik](https://user-images.githubusercontent.com/22545981/51389704-7ad88800-1b2d-11e9-84fe-2afd5b0a7bfc.png)

Settings vom Payment Icon Banner

![grafik](https://user-images.githubusercontent.com/22545981/51389985-42857980-1b2e-11e9-83a5-85cc82baf2d6.png)

![grafik](https://user-images.githubusercontent.com/22545981/51390017-53ce8600-1b2e-11e9-8ea1-af7e1bf2a4ab.png)


LG Klaus

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/51389995-4913f100-1b2e-11e9-8afa-2e088f675796.png)


![image](https://user-images.githubusercontent.com/6224096/51389944-24b81480-1b2e-11e9-905d-ddea70a5c95d.png)
![image](https://user-images.githubusercontent.com/6224096/51389961-313c6d00-1b2e-11e9-80b7-5e36a990da70.png)

Ich kann es gerade leider nicht wirklich nachstellen es passt bei mir :see_no_evil:

**Comment by klausmad** [comment]
Auch wenn alle Subshops unter /Deutsch/ liegen ? Du zeigst ja einen Sprachshop unter Englisch

![grafik](https://user-images.githubusercontent.com/22545981/51390144-b758b380-1b2e-11e9-86fc-fa081ac6f791.png)

**Comment by shyim** [comment]
Ich habs omg... Ich stell gleich eine Zip bereit des Plugins. Könntest du das testen dann? :)

**Comment by klausmad** [comment]
Kannst Du bitte dir vieleicht eine Testversion von ZENIT Payment oder Shipping  Icon laden ? Und die Farben unterschiedlich definieren wie oben angezeigt?

LG Klaus

**Comment by klausmad** [comment]
OK, warte auf das Update...teste es gleich... DANKE für Deine Mühe !

**Comment by shyim** [comment]
Das Update im Anhang :)
Hast ja echt das Frontend aufgehübscht, seit ich bei codeenterprise war :)

[FroshPerformance-master.zip](https://github.com/FriendsOfShopware/FroshPerformance/files/2773126/FroshPerformance-master.zip)

**Comment by klausmad** [comment]
Hallo,

ja man bemüht sich... mache das alles alleine, geht nur langsam voran, aber noch viel vor mir...

So, Update eingespielt... sieht gut aus, Farbzuordnung passt nun...nur das Bannerbild oben fehlt ..

![grafik](https://user-images.githubusercontent.com/22545981/51392450-5385b900-1b35-11e9-81bc-45d7a3cb6f3b.png)

**Comment by shyim** [comment]
Kommt das auch vom Plugin?

**Comment by klausmad** [comment]
So...mit HTML Komprimierung **deaktivieren** ist zuwenig...**nur mit Plugin Performance deinstallieren kommt das Bild wieder zurück**

So sollte es aussehen,

![grafik](https://user-images.githubusercontent.com/22545981/51392760-4ddca300-1b36-11e9-912e-c4c7bb4cfb49.png)

![grafik](https://user-images.githubusercontent.com/22545981/51392785-6220a000-1b36-11e9-8955-97684f11cb3f.png)

**Comment by klausmad** [comment]
Ja, das Bild kommt vom "Angebote Sales Countdown Banner (Zenit)" ... wenn Dein Plugin aktiv ist, ist das Bild weg...wird nicht aufgerufen... denke gleiche Ursache wie Hintergrundfarbe falsch...Hintergrundbild nicht da..ähnliches Muster ?

![grafik](https://user-images.githubusercontent.com/22545981/51393015-f854c600-1b36-11e9-8238-190dd6c1d408.png)

**Comment by klausmad** [comment]
Soll ich Dir zum Testen das Performance Plugin kurz aktivieren ?

**Comment by shyim** [comment]
Ich hab mir das Plugin schon geholt :) Schaue gerade nach einer Lösung

**Comment by shyim** [comment]
Ich war da jetzt 2,5 Stunden am Fehler suchen. Ich glaub ich habs jetzt. Ich teste das aber noch bisschen ob es endgültig klappt und auch mit jeder Shopware Version

**Comment by shyim** [comment]
Hey Klaus,
könntest du mal diese Zip probieren?

[FroshPerformance-master.zip](https://github.com/FriendsOfShopware/FroshPerformance/files/2777589/FroshPerformance-master.zip)

**Comment by klausmad** [comment]
Guten morgen, ist das die aktuelle Version aus dem SW Store oder neuer ?
Komm erst abends dazu.... LG Klaus

**Comment by shyim** [comment]
Das ist die neuste mit den Fix für das fehlende Logo :)

**Comment by shyim** [comment]
Gibt es mittlerweile etwas neues? :)

**Comment by klausmad** [comment]
Hallo,
konnte das Problem nun auch in meinem Testshop nachstellen, der letzte ZIP file hat aber **leider keine Änderung gebracht.**
Könnte Dir Zugang zu meinem Testshop geben... wohin darf ich den Zugang mailen ?

![grafik](https://user-images.githubusercontent.com/22545981/51519601-bd49df80-1e21-11e9-8244-6a249a453bf3.png)

![grafik](https://user-images.githubusercontent.com/22545981/51519705-10239700-1e22-11e9-81a3-16d39cfb25e2.png)

**Comment by klausmad** [comment]
Es häng klar mit Verwendung eines Hintergrundbildes zusammen.
Verwendet man Hintergrundfarbe ist alles OK, verwendet man ein Bild, wird das nicht angezeigt.

![grafik](https://user-images.githubusercontent.com/22545981/51519899-7f998680-1e22-11e9-8547-acdd429cadab.png)

**Comment by klausmad** [comment]
Plugin für den Banner = "Countdown Banner für Angebote, Sales & Nachrichten" von ZENIT
Mein Demoshop: SW 5.5.4 CE, sowei clean, also keine wesentlichen Plugins die Komplikationen bringen könnten.

**Comment by shyim** [comment]
Kannst gerne mailen an s.sayakci@shopware.com

**Comment by shyim** [comment]
Sollte nun mit den letzten Update behoben sein :)
