### ISSUE TITLE
robots.txt and sitemap should not be compress

### ISSUE THREAD

**Issue by resslinger** [FriendsOfShopware/FroshPerformance#14]
## Actual behaviour

    The robots.txt and the sitemap.xml will be compress with the plugin. So each entry is in one line.

## Expected behaviour

    The seo tool ryte.com recommends to show each entry in a separated line.

## Environment

PHP 7.0
SW 5.4.6

## Steps to reproduce

1. Call the robots.txt in the frontend without this plugin. Each entry is in a separated line.
2. Call the robots.txt in the frontend with this plugin. All entries are in one line.

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by hlohaus** [comment]
@shyim please fix it in 5.6 too

**Comment by resslinger** [comment]
@shyim very fast support - great work! :)
