### ISSUE TITLE
Fehlermeldung bei Theme-Kompilierung

### ISSUE THREAD

**Issue by pumpger** [FriendsOfShopware/FroshPerformance#16]
## Actual behaviour

    Bei installiertem Plugin bricht Theme-Kompilierung mit Fehlermeldung ab

## Environment

apache/nginx | php 7.2.14 | SW 5.5.5

Apache-Fehler 500
POST /shop/backend/cache/themeCacheWarmUp HTTP/1.0

Error

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Argument 6 passed to FroshPerformance\\Components\\Theme\\Compiler::__construct() must be an instance of Shopware\\Components\\Theme\\Compressor\\Js, instance of DneCustomJsCss\\Services\\CompressorDecorator given, called in /var/www/vhosts/domain/httpdocs/shop/var/cache/production_201901180958/proxies/ShopwareProduction3f64cbe1b24c669fca0e996acab132179938cab6ProjectContainer.php on line 4858 and defined in /var/www/vhosts/domain/httpdocs/shop/custom/plugins/FroshPerformance/Components/Theme/Compiler.php:51\nStack trace:\n#0 /var/www/vhosts/domain/httpdocs/shop/var/cache/production_201901180958/proxies/ShopwareProduction3f64cbe1b24c669fca0e996acab132179938cab6ProjectContainer.php(4858): FroshPerformance\\Components\\Theme\\Compiler->__construct('/var/www/vhosts...', Object(DneCustomJsCss\\Services\\LessCompilerDecorator), Object(Shopware\\Components\\Theme\\PathResolver), Object(Shopware\\Components\\Theme\\Inheritance), Object(Shopware\\Comp...\n', referer: https://domain/shop/backend/
    

## Steps to reproduce

1. Installation des Plugins übers Backend/Plugin-Manager
2. die 3 Einstellungen auf 'Nein' gesetzt
3. PlugIn aktiviert
4. Cache geleert
5. Theme kompilieren (bricht mit Meldung "Ein Fehler ist aufgetreten" ab. Protokoll-Eintrag siehe oben)

## Checklist

- [ x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ x] I am using the latest stable version of this plugin.

--

**Comment by shyim** [comment]
In den nächsten 10 Minuten müsste im ein Update angezeigt werden wo es dann behoben ist :smile:

**Comment by pumpger** [comment]
Hallo Shyim,
nachdem das Update eingespielt ist, kommt diese Fehlermeldung:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/vhosts/damain/httpdocs/shop/custom/plugins/DneCustomJsCss/Services/CompressorDecorator.php:58\nStack trace:\n#0 /var/www/vhosts/domain/httpdocs/shop/engine/Shopware/Components/Theme/Compiler.php(315): DneCustomJsCss\\Services\\CompressorDecorator->compress('/*! modernizr 3...')\n#1 /var/www/vhosts/domain/httpdocs/shop/engine/Shopware/Controllers/Backend/Cache.php(193): Shopware\\Components\\Theme\\Compiler->compileJavascript('new', Object(Shopware\\Models\\Shop\\Template), Object(Shopware\\Models\\Shop\\Shop))\n#2 /var/www/vhosts/domain/httpdocs/shop/engine/Library/Enlight/Controller/Action.php(193): Shopware_Controllers_Backend_Cache->themeCacheWarmUpAction()\n#3 /var/www/vhosts/domain/httpdocs/shop/engine/Library/Enlight/Controller/Dispatcher/Default.php(549): Enlight_Controller_Action->dispatch('themeCacheWarmU...')\n#4 /var/www/vhosts/domain/httpdo...\n', referer: https://domain/shop/backend/

**Comment by shyim** [comment]
Sollte nun endgültig behoben sein mit den Update :)
