### ISSUE TITLE
Performance goes down with 1.0.5

### ISSUE THREAD

**Issue by wotan3018** [FriendsOfShopware/FroshPerformance#17]
Hello!

We installed the Performance Plugin for our Shopware Shop 5.4.5 under www.zuhause-schwimmen.de.

At first we got a better page speed when we tested it in google page speed.

With the last update on 1.0.5 the Performance went down a lot.

Do we have to change anything?

For an answer i would be thankful.

BR

Thomas

# Prerequisites

Please, before creating this issue make sure that you read the [README](https://github.com/FriendsOfShopware/FroshPerformance/blob/master/README.md), that you are running the latest stable version of this plugin and that you already searched [other issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) to see if your problem or request was already reported.

! PLEASE REMOVE THIS PART AND LEAVE ONLY THE FOLLOWING SECTIONS IN YOUR REPORT !
---

## Actual behaviour

    Please describe the issue

## Expected behaviour

    What you expect to happen

## Environment

    Please provide information about the environment in which the issue occurs (e.g. PHP version, webserver, Shopware version, debugging information if you can provide).

## Steps to reproduce

1. First step
2. Second step
3. and so on...

## Checklist

- [ ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ ] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
1.0.5 has fixed the embedding of css of other plugins or themes.
That could be the reason why you had more points before.

Maybe post screenshots of the result :)

**Comment by wotan3018** [comment]
Hello!
Thanks for Your answer!
We have no screenshot from the page speed with 1.0.4. 
I can go back on 1.0.4 to make this screenshot. Perhaps it is a possibility for us to use the 1.0.4 instead of the new one.
BR
Thomas

**Comment by shyim** [comment]
You can download in Shopware Account the the version.
Maybe also save the output html of 1.0.4

**Comment by shyim** [comment]
Hey @wotan3018,
any updates?

**Comment by wotan3018** [comment]
Hello!
The performance got a little bit better with the 1.0.5, so we let it on this version.
But since yesterday the performance is very bad. I don´t know why, but on page speed we are roundabout at 6 at for the start page and 15 for article sites. Until friday it was much more better.

**Comment by wotan3018** [comment]
Hello!
We ae on the old values at Page Speed since yesterday. Maybe there was a failure at google.
I don´t know, if we should downgrade on 1.0.4 now.

**Comment by shyim** [comment]
Hey,
since all mostly all features are included in the Core. I will not further maintain this plugin
