### ISSUE TITLE
HTML minify destroys status mails

### ISSUE THREAD

**Issue by pascalheidmann-bedarf** [FriendsOfShopware/FroshPerformance#2]
## Actual behaviour
HTML status emails get crunched by minify HTML option -> everything gets into 1 line

## Expected behaviour

Optimizing output but not changing representation itself

## Environment
PHP 7.2, Apache, SW 5.5.4

## Steps to reproduce

1. Enable HTML minify
2. Send status mail

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
Fixed with https://github.com/FriendsOfShopware/FroshPerformance/commit/fdb3b0bb3a8892959b57912df199aafd49a21dc5
