### ISSUE TITLE
Shopware::REVISION is deprecated in 5.6

### ISSUE THREAD

**Issue by arosenhagen** [FriendsOfShopware/FroshPerformance#26]
## Actual behaviour

Fatal error: Uncaught Error: Undefined class constant 'REVISION' in FroshPerformance/Components/Theme/Compiler.php:81

## Expected behaviour

Use 'shopware.release.revision' from the DIC instead

## Environment

all

## Steps to reproduce

1. Install plugin

## Checklist

- [X] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [X] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
The plugin is currently not set compatible. I am not sure why this should be still available, cause most features are now in core :)
Just remove it :)

**Comment by resslinger** [comment]
solved
