### ISSUE TITLE
Can not install plugin (wrong dir name in zip archive)

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfShopware/FroshPerformance#5]
The dir inside of the div should not have the version string.

Relevant: https://github.com/mnaczenski/MNAddDSVGO/issues/1

See https://github.com/shopware/shopware/blob/6d43d6ac9eb346c1618a70c170fc50540dfff842/engine/Shopware/Bundle/PluginInstallerBundle/Service/PluginZipDetector.php#L57

**Comment by shyim** [comment]
The zip archive ist just a clone of the repository

**Comment by DanielRuf** [comment]
Yes but then the simple setup does not work as described.
https://github.com/FriendsOfShopware/FroshPerformance#installation

This should work like it was done with `FroshPerformance`, `FroshProfiler` and a few others.
