### ISSUE TITLE
500 error after install

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfShopware/FroshPerformance#6]
# Prerequisites

Use latest Shopware 5.5, install the plugin and use a child theme.

## Actual behaviour

Website does not work anymore, we just get a 500 error.
The HTML looks like 
```


</title>
--
  |  
  |  
  |  
  |  
  | <link href="

```

And then it stops.

## Expected behaviour

Shop should still work.

## Environment

PHP 7.2, Shopware 5.5

I'll add more info when I have some from the hosting provider.

## Steps to reproduce

1. First step
2. Second step
3. and so on...

## Checklist

- [ ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ ] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
The child theme is empty?

**Comment by DanielRuf** [comment]
No ti's not but the execution stopped there. I guess it was #1
