### ISSUE TITLE
Can not see any difference

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfShopware/FroshPerformance#7]
Actually I see no real difference after the installation.
The HTML looks the same.
Can you show a few before / after results (also from startpages of a demoshop)?

**Comment by stefanpoensgen** [comment]
**before**
![before](https://i.imgur.com/XaSsZXo.png)

**after**
![after](https://i.imgur.com/dkJounZ.png)

**Comment by shyim** [comment]
Is the plugin active and is the option enabled in the config?
Maybe config cache clearing :)

**Comment by DanielRuf** [comment]
> Is the plugin active and is the option enabled in the config?
> Maybe config cache clearing :)

Yes and yes.
Was the question by the plugin manager after the install not sufficient whichg asked me if I want to clear the caches. I clicked `yes` and saw no difference.

In contrast, the webp plugin changes were directly applied.

**Comment by DanielRuf** [comment]
@stefanpoensgen Unfortunately it still looks like the **before**  part on our website.

**Comment by DanielRuf** [comment]
> Is the plugin active and is the option enabled in the config?

It was by default.

**Comment by shyim** [comment]
I installed this plugin and webp together and cannot reproduce that

**Comment by DanielRuf** [comment]
Mh, maybe we'll further test and debug it but we'll probably wait for 5.6 and #2 solutions as this would affect all subshops.

**Comment by shyim** [comment]
I will close it then, cause we cannot reproduce that :)
