### ISSUE TITLE
Iframe payments not working

### ISSUE THREAD

**Issue by jakubpolomsky** [FriendsOfShopware/FroshPerformance#9]
## Actual behaviour

    Payment iframe not shown

## Expected behaviour

    Payment working

## Environment

- Shopware 5.5.4
- PHP 7.1
- Wirecard 1.3.2

## Steps to reproduce

1. Install wirecard from [here](https://github.com/wirecard/shopware-ee/releases)
2. Install Performance optimierungen from store or [here](https://store.shopware.com/frosh31872894918f/performance-optimierungen.html)
3. activate the extension
4. Activate payment method wirecard credit card
5. Make an order
6. Select wirecard credit card 
7. Check out

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshPerformance/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
Thanks to the Report!

So i have tested the change against your Plugin. It works now. Tag is also created. Should be deployed in the next minutes to the Store

**Comment by jakubpolomsky** [comment]
Thank you! :)

**Comment by shyim** [comment]
I will note that also for the Shopware 5.6 Release. Cause something very similar will be added there too :)
